### PR TITLE
Update package.json license to AGPL

### PR DESCRIPTION
**Pull request by sohkai**

### CODE REVIEW

**Comment by izqui** [comment]
I think we agreed to keeping the license in APM permissive to help boost adoption during offsite #1.

cc @mariapao @luisivan

**Comment by luisivan** [comment]
I don't remember, but I do believe we had a document about all this cc @mariapao

**Comment by mariapao** [comment]
@izqui @luisivan We agreed on AGPLv3 for this

**Comment by sohkai** [comment]
The current license doc for apm.js is also AGPL-3.0 so this is more of a consistency thing. Let's talk quickly tomorrow about it.

**Comment by sohkai** [comment]
We've decided to use LGPL3.0 instead.

**Pull request closed without merging**
