### PR TITLE
Fix timeout leak bug only by cancelling the timeout on success

### PR DESCRIPTION
**Pull request by dapplion**
The smallest change to fix an immediate necessity for the aragonCLI refactor.

If possible I would advise using a more lengthy but proper solution https://github.com/aragon/apm.js/pull/44 over this one.

### CODE REVIEW

**Comment by 0x6431346e** [comment]
There's one thing missing, if the first promise fails, the timeout will not be cleared.

See this solution: https://github.com/aragon/aragon-cli/blob/refactor/ipfs-cmds-2nd-try/packages/aragon-cli/src/lib/node/misc.js#L22

**Comment by 0x6431346e** [comment]
PS: I prefer #44 too!

**Comment by dapplion** [comment]
> There's one thing missing, if the first promise fails, the timeout will not be cleared.
> 
> See this solution: https://github.com/aragon/aragon-cli/blob/refactor/ipfs-cmds-2nd-try/packages/aragon-cli/src/lib/node/misc.js#L22

You are right hahaha, it's a pretty terrible pattern in my opinion, way to easy to cause leaks. Let's push for #44

**Comment by dapplion** [comment]
@0x6431346e Just force-pushed a fix covering the success and failure case, as you suggested in your comment

**Comment by 0x6431346e** [comment]
> > There's one thing missing, if the first promise fails, the timeout will not be cleared.
> > See this solution: [aragon/aragon-cli:ipfs-cmds-2nd-try/packages/aragon-cli/src/lib/node/misc.js@`refactor`#L22](https://github.com/aragon/aragon-cli/blob/refactor/ipfs-cmds-2nd-try/packages/aragon-cli/src/lib/node/misc.js#L22) [](/aragon/aragon-cli/blob/HEAD@{2019-12-05T15:21:38Z}/ipfs-cmds-2nd-try/packages/aragon-cli/src/lib/node/misc.js#L22)
> 
> You are right hahaha, it's a pretty terrible pattern in my opinion, way to easy to cause leaks. Let's push for #44

Yes, we need someone with write & publish access though!

**Pull request merged**
